#!/bin/sh
# Author: Salvador Zendejas

# -S Start
# -n process name 
# -a specify path

file_name=$(basename "$0")

# Remove the prefix 
if echo "$file_name" | grep -q "-"; then
  file_name=$(echo "$file_name" | cut -d'-' -f1)
fi
process_name=$(echo "$file_name" | sed 's/^S[0-9]*//')

case "$1" in
    start)
        echo "Starting daemon process $process_name"
        start-stop-daemon -S -n ${process_name} -a /usr/bin/${process_name} -- -d
        ;;
    stop)
        echo "Stopping process with SIGTERM"
        start-stop-daemon -K -n ${process_name}
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0